[package]
name = "zdb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "lib"
path = "src/lib.rs"

[cli]
name = "cli"
path = "src/bin/cli.rs"

[dependencies]
